### ISSUE TITLE
Ability to guarantee which ingressgateway gets which IP address

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/uds-package-metallb#8]
Currently, I'm only able to set one range of IP addresses for MetalLB to hand out, by setting the `IP_ADDRESS_POOL` variable.

The problem with this is, that there is no way for me to guarantee that a particular loadbalancer service will get a particular address, which makes it much more difficult to deal with figuring out how to set up my DNS properly.

Proposed solution:

- Eliminate the `IP_ADDRESS_POOL` variable
- Introduce 3 new variables: `IP_ADDRESS_ADMIN_INGRESSGATEWAY`, `IP_ADDRESS_KEYCLOAK_INGRESSGATEWAY`, and `IP_ADDRESS_TENANT_INGRESSGATEWAY`
- Create 3 IPAddressPools when deploying this package rather than just one. One named `ippool-admin-ingressgateway`, one named `ippool-keycloak-ingressgateway`, and one named `ippool-tenant-ingressgateway`. All 3 would use the `namespaceSelectors` and `serviceSelectors` functionality to automatically assign the correct pool to the correct ingressgateway.  See [the docs](https://metallb.universe.tf/configuration/_advanced_ipaddresspool_configuration/#reduce-scope-of-address-allocation-to-specific-namespace-and-service) for more info. In all 3 cases the string `/32` would be appended to the IP address provided to make it a CIDR range of exactly 1 address.
- Introduce new variable `DEFAULT_IP_ADDRESS_POOL` that allows the user to assign whatever other pool they want for all other use cases, associated with a 4th IpAddressPool named `ippool-default`. Alternatively, keep the `IP_ADDRESS_POOL` variable and use it for this.
- Add logic so that if any of the 3 new variables is not set then the associated IPAddressPool is not created

Pros:
- I'm able to guarantee with 100% certainty that each of the different ingressgateways get exactly the IP address that I want it to get, so that I am able to pre-configure my DNS rather than have to wait to configure it after deployment (and risk it possibly changing)

Cons:
- This package becomes coupled to the pattern that DUBBD uses for istio ingressgateways. If this package is not being used in concert with DUBBD it may do stuff for no reason.

**Comment by RothAndrew** [comment]
@andrewg-xyz let me know your thoughts. If you agree with this approach I'm happy to implement it.

**Comment by RothAndrew** [comment]
and @mjnagel and @Racer159

**Comment by mjnagel** [comment]
I generally like the idea of making this predictable with IPs. I don't know if every use case would want that, but its likely pretty common with DUBBD users. To the con of coupling with DUBBD I think we could potentially dodge that con by:
- Adding the same variables you mentioned
- If specific IPs are not provided for admin, tenant, keycloak do not create those pools
- Someone who wants to use this package more generically could just use the `DEFAULT_IP_ADDRESS_POOL` and get a more generic MetalLB experience

It still would mean some extra zarf vars, but those could be ignored by the end user without triggering any additional k8s resources. It does complicate the logic, but I tend to think this would make sense to wrap in a small helm chart so that you have more straightforward conditionals with gotmpl vs trying to handle this with just zarf vars and actions. Thoughts on that path?

**Comment by RothAndrew** [comment]
I think we were thinking on the same wavelength :) I already edited to say a lot of what you just said

**Comment by RothAndrew** [comment]
I'll go ahead and get started on implementing this, should be able to have a PR up by tomorrow most likely

**Comment by mjnagel** [comment]
Awesome, yeah this will be a great addition imo.
